//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace Summer_Reading_Challenge.Models
{
    public class Book
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string BookTitle { get; set; }
        public string Author { get; set; }
    }
}
